### ISSUE TITLE
Update google-api-client

### ISSUE THREAD

**Issue by Kumuluzz** [trifork/fastlane-plugin-translation#4]
The current version of this plugin requires version `0.9.20` of `google-api-client`. 

The latest version of Fastlane to support this is `2.38.1`. This means, than it's not possible to use Fastlane version `2.39` or higher due to the limitation from this plugin.

This plugin should be updated to the same `google-api-client` version as in the gemspec for Fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane.gemspec

```
# The Google API Client gem is *not* API stable between minor versions - hence the specific version locking here.
# If you upgrade this gem, make sure to upgrade the users of it as well.
spec.add_dependency 'google-api-client', '>= 0.13.1', '< 0.14.0' # Google API Client to access Play Publishing API
```

**Comment by CodeReaper** [comment]
I am unsure what the problem you are encountering is, because I am using fastlane version `2.58.0` without issues.

I do that using ruby version `2.4.2` from rbenv. I had to manually update the version of the fastlane gem to `2.58.0` in Gemfile.lock, but it works.

I am guessing the problem is that `bundle update` will select fastlane version `2.38.1` instead, but I am unsure why it does that.

**Comment by Kumuluzz** [comment]
With the release of Fastlane version 2.39.0, the `google-api-client` got bumped in the fastlane gemspec from `'~> 0.9.2'` to `'>= 0.12.0', '< 0.13.0'`. 

Gemspec for Fastlane 2.39.0:
https://github.com/fastlane/fastlane/blob/b8e0869a7ef268f45a9e6a357d6b56034a8c1818/fastlane.gemspec#L54

Gemspec for Fastlane 2.38.1:
https://github.com/fastlane/fastlane/blob/0a7a2486967a4ed21e178a2fa9d8c3d8e060fd76/fastlane.gemspec#L54

The gemspec for this translation plugin is specified to use version `'0.9.20'`. Whenever you run `bundle update`, then it tries to find the highest common denominator for `google-api-client` which happens to resolve to Fastlane 2.38.1.
https://github.com/trifork/fastlane-plugin-translation/blob/master/fastlane-plugin-translation.gemspec#L23

To resolve this issue, then the `google-api-client` simply needs to be bumped in the gemspec for this plugin. However it will most likely create problems since there has been breaking changes with the `google-api-client` gem.

**Comment by mri-scanomat** [comment]
I think it should be possible to update google-api-client to a higher version for this plugin. I have done it in the action before without problems. Have you tried updating it?

**Comment by CodeReaper** [comment]
I have removed the requirements so the plugin relies on the same versions as fastlane does. I have not experienced any issues as a result.
